# Generated by Django 2.2 on 2020-09-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('toys', 'Игрушки'), ('tools', 'Инструменты'), ('food', 'Еда'), ('tech', 'Бытовая техника'), ('chemicals', 'Бытовая химия'), ('other', 'Разное')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
