# Generated by Django 2.2 on 2020-09-26 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200926_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tools', 'Инструменты'), ('toys', 'Игрушки'), ('tech', 'Бытовая техника'), ('food', 'Еда'), ('other', 'Разное'), ('chemicals', 'Бытовая химия')], default='other', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
