# Generated by Django 2.2 on 2020-09-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200926_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('moderated', 'Модерирован'), ('other', 'Не модерирован')], default='not moderated', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Еда'), ('tools', 'Инструменты'), ('other', 'Разное'), ('toys', 'Игрушки'), ('chemicals', 'Бытовая химия'), ('tech', 'Бытовая техника')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
