# Generated by Django 2.2 on 2020-09-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200926_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'Разное'), ('food', 'Еда'), ('tools', 'Инструменты'), ('toys', 'Игрушки'), ('tech', 'Бытовая техника'), ('chemicals', 'Бытовая химия')], default='other', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('not moderated', 'Не модерирован'), ('moderated', 'Модерирован')], default='not moderated', max_length=20, verbose_name='Статус'),
        ),
    ]
