# Generated by Django 2.2 on 2020-09-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200926_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Task', max_length=20, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('chemicals', 'Бытовая химия'), ('tech', 'Бытовая техника'), ('other', 'Разное'), ('toys', 'Игрушки'), ('food', 'Еда'), ('tools', 'Инструменты')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
