# Generated by Django 2.2 on 2020-09-26 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200926_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tech', 'Бытовая техника'), ('chemicals', 'Бытовая химия'), ('other', 'Разное'), ('tools', 'Инструменты'), ('food', 'Еда'), ('toys', 'Игрушки')], default='other', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='webapp.Status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='Не модерирован', max_length=20, verbose_name='Название статуса'),
        ),
    ]
