# Generated by Django 2.2 on 2020-09-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200926_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('chemicals', 'Бытовая химия'), ('other', 'Разное'), ('tools', 'Инструменты'), ('toys', 'Игрушки'), ('tech', 'Бытовая техника'), ('food', 'Еда')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
