# Generated by Django 2.2 on 2020-09-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200926_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('toys', 'Игрушки'), ('tech', 'Бытовая техника'), ('food', 'Еда'), ('chemicals', 'Бытовая химия'), ('other', 'Разное'), ('tools', 'Инструменты')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
