# Generated by Django 2.2 on 2020-10-23 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200926_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'Разное'), ('food', 'Еда'), ('toys', 'Игрушки'), ('tech', 'Бытовая техника'), ('tools', 'Инструменты'), ('chemicals', 'Бытовая химия')], default='other', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
